// Code generated by gotsrpc https://github.com/foomo/gotsrpc/v2  - DO NOT EDIT.

package service

import (
	io "io"
	ioutil "io/ioutil"
	http "net/http"
	time "time"

	github_com_foomo_busser_table "github.com/foomo/busser/table"
	gotsrpc "github.com/foomo/gotsrpc/v2"
)

const (
	ServiceGoTSRPCProxyCommit       = "Commit"
	ServiceGoTSRPCProxyDelete       = "Delete"
	ServiceGoTSRPCProxyGetCommitted = "GetCommitted"
	ServiceGoTSRPCProxyGetVersion   = "GetVersion"
	ServiceGoTSRPCProxyList         = "List"
	ServiceGoTSRPCProxyValidate     = "Validate"
)

type ServiceGoTSRPCProxy struct {
	EndPoint string
	service  Service
}

func NewDefaultServiceGoTSRPCProxy(service Service) *ServiceGoTSRPCProxy {
	return NewServiceGoTSRPCProxy(service, "/services/busser")
}

func NewServiceGoTSRPCProxy(service Service, endpoint string) *ServiceGoTSRPCProxy {
	return &ServiceGoTSRPCProxy{
		EndPoint: endpoint,
		service:  service,
	}
}

// ServeHTTP exposes your service
func (p *ServiceGoTSRPCProxy) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodOptions {
		return
	} else if r.Method != http.MethodPost {
		gotsrpc.ErrorMethodNotAllowed(w)
		return
	}
	defer io.Copy(ioutil.Discard, r.Body) // Drain Request Body

	funcName := gotsrpc.GetCalledFunc(r, p.EndPoint)
	callStats, _ := gotsrpc.GetStatsForRequest(r)
	callStats.Func = funcName
	callStats.Package = "github.com/foomo/busser/service"
	callStats.Service = "Service"
	switch funcName {
	case ServiceGoTSRPCProxyCommit:
		var (
			args []interface{}
			rets []interface{}
		)
		var (
			arg_id      github_com_foomo_busser_table.ID
			arg_version github_com_foomo_busser_table.Version
		)
		args = []interface{}{&arg_id, &arg_version}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		executionStart := time.Now()
		commitRet := p.service.Commit(arg_id, arg_version)
		callStats.Execution = time.Since(executionStart)
		rets = []interface{}{commitRet}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyDelete:
		var (
			args []interface{}
			rets []interface{}
		)
		var (
			arg_id       github_com_foomo_busser_table.ID
			arg_versions []github_com_foomo_busser_table.Version
		)
		args = []interface{}{&arg_id, &arg_versions}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		executionStart := time.Now()
		deleteErr := p.service.Delete(arg_id, arg_versions)
		callStats.Execution = time.Since(executionStart)
		rets = []interface{}{deleteErr}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyGetCommitted:
		var (
			args []interface{}
			rets []interface{}
		)
		var (
			arg_id github_com_foomo_busser_table.ID
		)
		args = []interface{}{&arg_id}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		executionStart := time.Now()
		getCommittedT, getCommittedVt, getCommittedErr := p.service.GetCommitted(arg_id)
		callStats.Execution = time.Since(executionStart)
		rets = []interface{}{getCommittedT, getCommittedVt, getCommittedErr}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyGetVersion:
		var (
			args []interface{}
			rets []interface{}
		)
		var (
			arg_id      github_com_foomo_busser_table.ID
			arg_version github_com_foomo_busser_table.Version
		)
		args = []interface{}{&arg_id, &arg_version}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		executionStart := time.Now()
		getVersionT, getVersionVt, getVersionErr := p.service.GetVersion(arg_id, arg_version)
		callStats.Execution = time.Since(executionStart)
		rets = []interface{}{getVersionT, getVersionVt, getVersionErr}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyList:
		var (
			args []interface{}
			rets []interface{}
		)
		executionStart := time.Now()
		listRet, listRet_1 := p.service.List()
		callStats.Execution = time.Since(executionStart)
		rets = []interface{}{listRet, listRet_1}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	case ServiceGoTSRPCProxyValidate:
		var (
			args []interface{}
			rets []interface{}
		)
		var (
			arg_id github_com_foomo_busser_table.ID
		)
		args = []interface{}{&arg_id}
		if err := gotsrpc.LoadArgs(&args, callStats, r); err != nil {
			gotsrpc.ErrorCouldNotLoadArgs(w)
			return
		}
		executionStart := time.Now()
		validateT, validateVt, validateErr := p.service.Validate(arg_id)
		callStats.Execution = time.Since(executionStart)
		rets = []interface{}{validateT, validateVt, validateErr}
		if err := gotsrpc.Reply(rets, callStats, r, w); err != nil {
			gotsrpc.ErrorCouldNotReply(w)
			return
		}
		gotsrpc.Monitor(w, r, args, rets, callStats)
		return
	default:
		gotsrpc.ClearStats(r)
		gotsrpc.ErrorFuncNotFound(w)
	}
}
